### ISSUE TITLE
401 error in tilejson?

### ISSUE THREAD

**Issue by heaversm** [lliss/tile-converter#2]
```
/usr/local/lib/node_modules/tessera/server.js:43
        throw err;
              ^
Error: Server returned HTTP 401
    at Get.handleClientRequest (/usr/local/lib/node_modules/tilejson/node_modules/get/lib/index.js:151:23)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socketOnData (http.js:1584:20)
    at TCP.onread (net.js:528:27)
vagrant@tile-converter:/$
```

Any idea why I'm getting this error? Used to be able to successfully run the server using this command (after vagrant ssh):

`tessera tmstyle:///vagrant/light.tm2`

**Comment by heaversm** [comment]
needed to run `vagrant provision`
